module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "aqua-spring": "var(--aqua-spring)",
        "athens-gray": "var(--athens-gray)",
        azalea: "var(--azalea)",
        "barley-white": "var(--barley-white)",
        black: "var(--black)",
        "black-60": "var(--black-60)",
        boulder: "var(--boulder)",
        buttercup: "var(--buttercup)",
        california: "var(--california)",
        chablis: "var(--chablis)",
        "chateau-green": "var(--chateau-green)",
        cinnabar: "var(--cinnabar)",
        "curious-blue": "var(--curious-blue)",
        "dodger-blue": "var(--dodger-blue)",
        "eastern-blue": "var(--eastern-blue)",
        "fringy-flower": "var(--fringy-flower)",
        geyser: "var(--geyser)",
        "hawkes-blue": "var(--hawkes-blue)",
        iceberg: "var(--iceberg)",
        "jungle-green": "var(--jungle-green)",
        "lavender-blush": "var(--lavender-blush)",
        mariner: "var(--mariner)",
        mystic: "var(--mystic)",
        "oslo-gray": "var(--oslo-gray)",
        panache: "var(--panache)",
        pewter: "var(--pewter)",
        "pickled-bluewood": "var(--pickled-bluewood)",
        pomegranate: "var(--pomegranate)",
        porcelain: "var(--porcelain)",
        sail: "var(--sail)",
        sazerac: "var(--sazerac)",
        white: "var(--white)",
        "white-10": "var(--white-10)",
        "white-catskill-white": "var(--white-catskill-white)",
        "yukon-gold": "var(--yukon-gold)",
        zanah: "var(--zanah)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "arial-narrow": "var(--arial-narrow-font-family)",
        "inter-regular": "var(--inter-regular-font-family)",
        "noto-sans-JP-bold": "var(--noto-sans-JP-bold-font-family)",
        "noto-sans-JP-demilight": "var(--noto-sans-JP-demilight-font-family)",
        "noto-sans-JP-medium": "var(--noto-sans-JP-medium-font-family)",
        "noto-sans-JP-medium-underline":
          "var(--noto-sans-JP-medium-underline-font-family)",
        "noto-sans-JP-semibold": "var(--noto-sans-JP-semibold-font-family)",
        "noto-sans-JP-semibold-upper":
          "var(--noto-sans-JP-semibold-upper-font-family)",
        "semantic-button": "var(--semantic-button-font-family)",
        "semantic-cell-upper": "var(--semantic-cell-upper-font-family)",
        "semantic-data": "var(--semantic-data-font-family)",
        "semantic-heading-1": "var(--semantic-heading-1-font-family)",
        "semantic-heading-2": "var(--semantic-heading-2-font-family)",
        "semantic-input": "var(--semantic-input-font-family)",
        "semantic-label": "var(--semantic-label-font-family)",
        "semantic-label-upper": "var(--semantic-label-upper-font-family)",
        "semantic-link": "var(--semantic-link-font-family)",
        "semantic-options": "var(--semantic-options-font-family)",
        "semantic-textarea": "var(--semantic-textarea-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
